### ISSUE TITLE
Implement null safety

### ISSUE THREAD

**Issue by 12people** [zanderso/delaunay.dart#11]
Dart is becoming a null safe language and Google is [asking package maintainers](https://dart.dev/null-safety/migration-guide) to make their packages null safe. Until they do, developers are being asked to hold off on implementing null safety.

As I'm starting out with a null safe project and would like to use this library, I would love it if this package was migrated.

**Comment by zanderso** [comment]
Done in https://github.com/zanderso/delaunay.dart/pull/13
